import com.itextpdf.text.*
import com.itextpdf.text.pdf.PdfWriter
import java.io.FileOutputStream
import java.util.*


class compra(idCompra:Int, idCliente:Int, productosComprados:ArrayList<producto_comprado>){
    var idCompra = idCompra
    var idCliente = idCliente
    var productoComprados = productosComprados
    var urlPdf = ""
    var total = 0.0
    private val catFont: Font = Font(Font.FontFamily.TIMES_ROMAN, 18f,
            Font.BOLD)
    private val subFont: Font = Font(Font.FontFamily.TIMES_ROMAN, 16f,
            Font.BOLD)
    private val smallBold: Font = Font(Font.FontFamily.TIMES_ROMAN, 12f,
            Font.BOLD)

    //@author github.com/equetzal -> Enya
    init{
        productosComprados.forEach {
            total += it.precioFinalProductos
        }
        urlPdf = generarPdf()
    }

    private fun addEmptyLine(paragraph: Paragraph, number: Int) {
        for (i in 0 until number) {
            paragraph.add(Paragraph(" "))
        }
    }

    @Throws(DocumentException::class)
    private fun addTitlePage(document: Document) {
        val preface = Paragraph()
        // We add one empty line
        addEmptyLine(preface, 1)
        // Lets write a big header
        preface.add(Paragraph("Recibo de compra: $idCompra", catFont))
        addEmptyLine(preface, 1)
        // Will create: Report generated by: _name, _date
        preface.add(Paragraph(
                "Cliente número: $idCliente" + ",   Fecha: " + Date(),  //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$
                smallBold))
        addEmptyLine(preface, 2)
        document.add(preface)
    }
    fun generarPdf() : String{
        println("Generando PDF de compra")

        val path = "./files/receipts/"
        val file = "$path$idCompra.pdf"
        val document = Document()
        PdfWriter.getInstance(document, FileOutputStream(file))

        document.open()
        addTitlePage(document)
        var paragraph = Paragraph()
        productoComprados.forEach{
            paragraph.add(Paragraph("ID producto: "+ it.idProducto, smallBold))
            paragraph.add(Paragraph("Cantidad: "+ it.cantidadProducto, smallBold))
            paragraph.add(Paragraph("Precio unitario: "+ it.precioUnitario, smallBold))
            paragraph.add(Paragraph("Subtotal: "+ it.precioFinalProductos, smallBold))
        }
        paragraph.add(Paragraph("Total: $total", smallBold))
        document.add(paragraph)
        document.close()
        return file
    }


}